[package]
name = "romad"
version = "0.1.0"
authors = ["Ben Johnston"]
edition = "2018"
license-file = "LICENSE"
keywords = ["hashicorp", "nomad"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
